### ISSUE TITLE
pi_aux = p[i+self.nl] IndexError: list index out of range

### ISSUE THREAD

**Issue by korryu3** [TechC-SugarCane/ObjectDetection#7]
tinyモデルを`train_aux.py`で学習させるとこれが出る

### 学習時のコマンド
```sh
python train_aux.py --workers 8 --batch-size 8 --data yolov7-datasets/sugarcane/data.yaml --cfg cfg/training/yolov7-tiny.yaml --weights checkpoints/yolov7-tiny.pt --name yolov7-tiny-sugarcane --hyp data/hyp.scratch.sugarcane.yaml --epochs 200 --device 0
```

### error
```tb
Traceback (most recent call last):
  File "C:\Users\ryuya\Documents\TECH.C\Ishigaki\ObjectDetection\train_aux.py", line 612, in <module>
    train(hyp, opt, device, tb_writer)
  File "C:\Users\ryuya\Documents\TECH.C\Ishigaki\ObjectDetection\train_aux.py", line 362, in train
    loss, loss_items = compute_loss_ota(pred, targets.to(device), imgs)  # loss scaled by batch_size
  File "C:\Users\ryuya\Documents\TECH.C\Ishigaki\ObjectDetection\utils\loss.py", line 1214, in __call__
    pi_aux = p[i+self.nl]
IndexError: list index out of range
```

**Comment by korryu3** [comment]
tinyはtrain.pyで実行せよとのこと
